name: CI

on:
  workflow_dispatch:
  push:
    branches: [ 'main' ]

jobs:
  dokka:
    runs-on: ubuntu-latest

    steps:
      - name: Clone master branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
          submodules: "recursive"
          token: ${{ secrets.GITHUB_TOKEN}}
          path: "./EzXHelper"

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('/*.gradle') }}-${{ hashFiles('/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set git identity
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Accept Android SDK Licenses
        run: |
          yes | ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses &> /dev/null || true

      - name: Build KDoc
        run: |
          cd ./EzXHelper
          chmod +x gradlew
          ./gradlew :EzXHelper:dokkaHtml

      - name: Push to gh-pages
        if: success()
        run: |
          mkdir gh-pages
          cd EzXHelper
          cp ./EzXHelper/build/dokka/html/* ../gh-pages -rf
          git checkout gh-pages
          echo -e ".gradle\nEzXHelper/build" > .gitignore
          cp ../gh-pages . -rf
          if [[ `git status --porcelain` ]]; then
            git add .
            git commit -m "Auto commit at $(date)"
            git push origin gh-pages
          else
            echo "Skip push without change"
          fi
